-- Run this once in Supabase: SQL Editor > New query > Run.
create table if not exists public.study_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  state_json jsonb not null,
  revision integer not null default 0,
  updated_at timestamptz not null default now(),
  updated_by_device text
);

create table if not exists public.study_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  revision integer not null,
  state_json jsonb not null,
  created_at timestamptz not null default now(),
  device_id text,
  unique (user_id, revision)
);

create index if not exists idx_study_snapshots_user_created
  on public.study_snapshots (user_id, created_at desc);

alter table public.study_accounts enable row level security;
alter table public.study_snapshots enable row level security;

-- StudyBloom's Vercel server validates the signed-in user and accesses these
-- tables with the private service-role key. Browser clients cannot read them.
